[package]
name = "ethereal-mail-test-account"
version = "0.1.0"
authors = ["Philipp Korber <p.korber@1aim.com>"]
edition = "2018"

[dependencies]
xdg = "2.2.0"
reqwest = "0.9.10"
serde = { version="1.0.89", features=["derive"] }
serde_json = "1.0.39"
failure = "0.1.5"
log = "0.4.6"